<script lang="ts">
  import {cancel,health,status,submit,type RunPodJob} from './api';
  let tab:'create'|'library'|'settings'='create', prompt='cinematic portrait in soft morning light', seed=Math.floor(Math.random()*2_147_483_647), width=768,height=1024;
  let configured=false,busy=false,message='Checking gateway…',job:RunPodJob|null=null,images:string[]=[];
  let workflowText=localStorage.getItem('flujo.workflow')||'';
  health().then(h=>{configured=h.configured;message=h.configured?'RunPod Serverless ready':'Add server environment variables'}).catch(e=>message=e.message);
  const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
  function workflow(){if(!workflowText)throw new Error('Paste a ComfyUI API workflow in Settings');let text=workflowText.replaceAll('{{PROMPT}}',prompt.replaceAll('"','\\"')).replaceAll('{{SEED}}',String(seed)).replaceAll('{{WIDTH}}',String(width)).replaceAll('{{HEIGHT}}',String(height));return JSON.parse(text)}
  function outputImages(output:unknown):string[]{const found:string[]=[];const walk=(x:unknown)=>{if(typeof x==='string'&&(x.startsWith('data:image/')||x.startsWith('https://')||x.startsWith('http://')))found.push(x);else if(Array.isArray(x))x.forEach(walk);else if(x&&typeof x==='object')Object.values(x).forEach(walk)};walk(output);return found}
  async function generate(){try{busy=true;images=[];message='Submitting…';job=await submit(workflow());message=`Job ${job.id} queued`;while(job.status!=='COMPLETED'){if(['FAILED','CANCELLED','TIMED_OUT'].includes(job.status||''))throw new Error(job.error||job.status);await sleep(1500);job=await status(job.id);message=job.status||'Running'}images=outputImages(job.output);message=images.length?`${images.length} image(s) complete`:'Complete; inspect raw output in RunPod'}catch(e){message=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function cancelJob(){if(job?.id){await cancel(job.id);busy=false;message='Cancelled'}}
  function save(){JSON.parse(workflowText);localStorage.setItem('flujo.workflow',workflowText);message='Workflow saved';tab='create'}
</script>
<svelte:head><title>Flujo</title></svelte:head>
<header><b><i></i>flujo</b><nav><button class:active={tab==='create'} onclick={()=>tab='create'}>Create</button><button class:active={tab==='library'} onclick={()=>tab='library'}>Library</button><button class:active={tab==='settings'} onclick={()=>tab='settings'}>Settings</button></nav><span class="status"><em class:ok={configured}></em>{message}</span></header>
{#if tab==='create'}<main><section class="results">{#each images as image}<img src={image} alt="Generated result">{/each}{#if busy}<div class="loading">{message}</div>{/if}</section><section class="composer"><textarea bind:value={prompt} placeholder="Describe an image"></textarea><div><label>Seed <input type="number" bind:value={seed}></label><label>W <input type="number" bind:value={width}></label><label>H <input type="number" bind:value={height}></label>{#if busy}<button class="danger" onclick={cancelJob}>Cancel</button>{/if}<button class="go" disabled={busy||!configured} onclick={generate}>Generate</button></div></section></main>
{:else if tab==='library'}<main><h1>Library</h1><p>Persistent history is the next adapter; completed results remain visible for this session.</p><section class="results">{#each images as image}<img src={image} alt="Generated result">{/each}</section></main>
{:else}<main><h1>Settings</h1><section class="card"><h2>ComfyUI API workflow</h2><p>Export with “Workflow → Export (API)”. Use <code>&#123;&#123;PROMPT&#125;&#125;</code>, <code>&#123;&#123;SEED&#125;&#125;</code>, <code>&#123;&#123;WIDTH&#125;&#125;</code>, and <code>&#123;&#123;HEIGHT&#125;&#125;</code> in input values you want Flujo to replace.</p><textarea class="workflow" bind:value={workflowText}></textarea><button class="go" onclick={save}>Validate & save</button></section><section class="card"><h2>Gateway</h2><p>API credentials are server-side only. Configure <code>RUNPOD_API_KEY</code> and <code>RUNPOD_ENDPOINT_ID</code> on the Gleam service.</p></section></main>{/if}
<style>
  :global(*){box-sizing:border-box}:global(body){margin:0;background:#0d0f12;color:#f5f7fa;font:14px/1.5 Inter,system-ui}:global(button),:global(input),:global(textarea){font:inherit;color:inherit}header{height:60px;border-bottom:1px solid #2a2f38;display:flex;align-items:center;padding:0 22px;gap:28px;position:sticky;top:0;background:#0d0f12e8;backdrop-filter:blur(14px)}header b{font-size:20px}header i{display:inline-block;width:25px;height:25px;border-radius:8px;background:linear-gradient(135deg,#7d8cff,#a07cff);vertical-align:-7px;margin-right:8px}nav{display:flex;gap:5px}button{border:0;border-radius:9px;background:transparent;padding:9px 12px;cursor:pointer;color:#9299a5}button.active,button:hover{background:#1b1f25;color:white}.status{margin-left:auto;color:#9299a5}.status em{width:8px;height:8px;border-radius:50%;display:inline-block;background:#ff7181;margin-right:8px}.status em.ok{background:#55d69d}main{max-width:1120px;margin:auto;padding:32px 20px 180px}.results{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.results img,.loading{width:100%;aspect-ratio:3/4;border-radius:16px;background:#1b1f25;object-fit:cover}.loading{display:grid;place-items:center;color:#9299a5}.composer{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);width:min(820px,calc(100vw - 28px));background:#171a1fee;border:1px solid #39404b;border-radius:18px;padding:12px;box-shadow:0 24px 70px #0009}.composer textarea{width:100%;height:70px;resize:none;background:none;border:0;outline:0}.composer>div{display:flex;gap:10px;align-items:center;border-top:1px solid #2a2f38;padding-top:10px}.composer label{color:#9299a5}.composer input{width:90px;background:#1b1f25;border:1px solid #2a2f38;border-radius:7px;padding:7px}.go{background:#7d8cff;color:white;margin-left:auto}.go:disabled{opacity:.4}.danger{color:#ff9ca8}.card{background:#15181d;border:1px solid #2a2f38;border-radius:16px;padding:18px;margin-bottom:14px}.card p{color:#9299a5}.workflow{width:100%;height:380px;background:#101216;border:1px solid #2a2f38;border-radius:10px;padding:12px;font-family:monospace;font-size:12px;display:block;margin:14px 0}@media(max-width:700px){nav{display:none}.status{max-width:150px;white-space:nowrap;overflow:hidden}.results{grid-template-columns:repeat(2,1fr)}.composer label:nth-child(n+2){display:none}}
</style>
